## Playwright and Typscript in AWS Pipline

version: 0.2

phases:
 install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm ci
      - echo Installing Playwright browsers...
      - npx playwright install --with-deps
 build:
    commands:
      - echo Running tests...
      - npx playwright test
artifacts:
 files:
    - '**/*'
 base-directory: 'playwright-report'


